### ISSUE TITLE
[Question] How to delete a character string that is not related to completion.

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lsp#327]
# How to delete a character string that is not related to completion.
As shown in the screenshot below, `(${1:x})$` comes after the `drop`. Is it possible to remove it?

<img width="811" alt="スクリーンショット 2020-08-26 6 19 46" src="https://user-images.githubusercontent.com/3197942/91230458-8018a280-e766-11ea-8771-f493d23fbc1e.png">

In addition, since various patterns of character strings are added after the keyword, it is difficult to remove them with regular expressions.

## Environment Information

 * nvim-lsp version (SHA1): fc9d94ef006e082596c2e8724eb3f1c92ff203c7 

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-nightly-131-g8c49e3d50

 * `:checkhealth` or `:CheckHealth` result(neovim only): All OK

### Plugins
```toml
[[plugins]]	
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = 'source ~/.config/nvim/rc/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'neovim/nvim-lsp'
hook_source = 'luafile ~/.config/nvim/lua/lsp.lua'
on_ft = ['rust']
```

### deoplete settings
```vim
call deoplete#custom#option('min_pattern_length', 2)

call deoplete#custom#option('sources', {
    \ 'rust': ['buffer', 'lsp'],
    \})
   
call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter'
    \])

inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"

call deoplete#enable()
```

### lua settings
```lua
local lsp = require "nvim_lsp"
lsp.rust_analyzer.setup{}
```
